### ISSUE TITLE
data security group error

### ISSUE THREAD

**Issue by Jolin-blank** [tencentcloudstack/terraform-provider-tencentcloud#1334]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x308664c]

goroutine 276 [running]:
github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud.(*VpcService).DescribeSecurityGroupPolices.func1()
        github.com/tencentcloudstack/terraform-provider-tencentcloud/tencentcloud/service_tencentcloud_vpc.go:1764 +0xb4c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/wait.go:22 +0x56
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:103 +0x18c
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:80 +0x1bd

Error: The terraform-provider-tencentcloud_v1.78.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

data "tencentcloud_security_groups" "ops" {
  name = "Basic-PROD-OpsControl"
}

**Comment by Kagashino** [comment]
Hi @Jolin-blank 
That's because the protocol template typed security rule are not supported, the next version will fix this problem

**Comment by Jolin-blank** [comment]
do you have fix it at the lastest version?

**Comment by Kagashino** [comment]
> do you have fix it at the lastest version?

This problem was fixed v1.78.6  https://github.com/tencentcloudstack/terraform-provider-tencentcloud/pull/1315
